run:
  skip-dirs:
    - assets
severity:
  default-severity: warning
linters:
  enable:
    - cyclop
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exhaustivestruct
    # - forbidigo removes debugging and printing
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox triggers on todo and etc. turn on later
    - gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomnd extremely controversial rule
    - gomoddirectives
    - gomodguard
    - gosec
    - gosimple
    - govet
    - depguard
    - ifshort
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - promlinter
    - predeclared
    - rowserrcheck
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - unparam
    - unused
    - whitespace
    - wrapcheck
linters-settings:
  goimports:
    local-prefixes: github.com/TemirkhanN/rpg
  funlen:
    lines: 100
  cyclop:
    max-complexity: 15
