on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: code-quality-check
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - name: test
        run: go test -v ./...
